### ISSUE TITLE
panic error

### ISSUE THREAD

**Issue by Biedubbeljoe** [EgeBalci/ARCANUS#11]
After installing and selecting option 2, to make a windows payload and entering the IP and port number 8080, I get this error:

![1](https://cloud.githubusercontent.com/assets/15264264/17968582/deaf955c-6acd-11e6-8723-eb2d9d168583.png)

Go has been installed.

**Comment by EgeBalci** [comment]
I just tested the version 1.5.6 and it worked well, if you give me more info about your payload your and your system i may help you more first try running it on an another system it may be an exceptional error.
