### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by Dark0x0Spy** [EgeBalci/ARCANUS#2]
bash: ./ARCANUS: cannot execute binary file: exec format error
how to solve?

**Comment by EgeBalci** [comment]
I am guessing there can be some compability problem, try to compile golang code on your system. I can help more İf you give me more details like witch OS you are using and what is your systems architecture?

**Comment by Dark0x0Spy** [comment]
i am using kali linux latest version i686.

**Comment by EgeBalci** [comment]
If you are using 32 bit system you need to compile go code for 32 bit binary. This binary file is build for 64 bit systems, type "apt-get install golang " for installing latest golang version on your kali then type "go build ARCANUS.go" to compile the code for your system.
