### ISSUE TITLE
AV Scan 

### ISSUE THREAD

**Issue by BestAndroid** [EgeBalci/ARCANUS#4]
It would be even better if u give us the link of the site where you scan the payloads....

**Comment by EgeBalci** [comment]
You can scan here https://nodistribute.com/ but please don't submit ARCANUS
payloads to any other virus scanning sites, other scanner sites distributes
samples to anti virus companies for  deeper analyze, that meens less
antivirus evasion for us ;)

2016-04-07 18:00 GMT+03:00 BestAndroid notifications@github.com:

**Comment by BestAndroid** [comment]
Thanks bro...and don't u worry I will never upload any payload to any other site than this.... :)
