### ISSUE TITLE
golang problem 

### ISSUE THREAD

**Issue by GoldenHex** [EgeBalci/ARCANUS#5]
i use kali linux sanna but i can't run the script because i don't have golang on my system and i don't know which repository i must use  to install it ?

**Comment by EgeBalci** [comment]
use "apt-get install golang"

**Comment by GoldenHex** [comment]
![screenshot from 2016-04-08 16 22 20](https://cloud.githubusercontent.com/assets/8321366/14388453/bce0303c-fd9d-11e5-9c18-6ab0831bd0e0.png)

**Comment by EgeBalci** [comment]
I think this is because of your old kali version, try "apt-get install go" if you still can't download the repo you can install golang here manualy https://golang.org/dl/
